name: Build Docker Image, Push it to Github Packages and Send notification to Slack Afterwards
on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$GITHUB_RUN_NUMBER
    - name: Docker Login
      run: echo  ${{ secrets.REG_TOKEN }} | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
    - name: Image Push
      id: step_onr
      run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$GITHUB_RUN_NUMBER
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=thechetantalwar
          -Dsonar.projectKey=thechetantalwar_actions-demo
  notify:
    runs-on: ubuntu-latest
    if: always()
    needs: build
    steps:
      - name: Send a Notification
        id: notify
        uses: thechetantalwar/slack-notify@v2
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          message: "Github Action Completed for ${{ github.repository	 }} with Build Number ${{ github.run_number }} and the outcome is  ${{ needs.build.result }}."
